#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outputPath = path.join(rootDir, 'src', 'config', 'env.generated.ts');

const parseEnvFile = content => {
  const result = {};
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const delimiterIndex = line.indexOf('=');
    if (delimiterIndex <= 0) {
      continue;
    }

    const key = line.slice(0, delimiterIndex).trim();
    let value = line.slice(delimiterIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  return result;
};

const escapeForTs = value => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const envContent = fs.existsSync(envPath)
  ? fs.readFileSync(envPath, 'utf8')
  : '';
const env = parseEnvFile(envContent);

const googleClientId = env.GOOGLE_CLIENT_ID || 'REPLACE_WITH_GOOGLE_CLIENT_ID';
const githubClientId = env.GITHUB_CLIENT_ID || 'REPLACE_WITH_GITHUB_CLIENT_ID';
const openClawOrigin = env.OPENCLAW_ORIGIN || 'http://localhost:3001';
const oauthBackendOrigin = env.OAUTH_BACKEND_ORIGIN || openClawOrigin;

const output = `// This file is auto-generated by scripts/generate-env.js
// Do not commit secrets here.
export const GOOGLE_CLIENT_ID = '${escapeForTs(googleClientId)}';
export const GITHUB_CLIENT_ID = '${escapeForTs(githubClientId)}';
export const OPENCLAW_ORIGIN = '${escapeForTs(openClawOrigin)}';
export const OAUTH_BACKEND_ORIGIN = '${escapeForTs(oauthBackendOrigin)}';
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Generated ${path.relative(rootDir, outputPath)}`);
